version: 'latest'

services:

  app:
    build:
      context: ./node
    container_name: app
    entrypoint:
      [
        "dockerize",
        "-wait",
        "tcp://db:3306",
        "-timeout",
        "20s",
        "node",
        "server.js"
      ]
    networks:
      - app-network
    image: jeansouza007/node
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: jeansouza007/nginx
    container_name: nginx
    networks:
      - app-network
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  app-network:
    name: app-network
    driver: bridge
